# Generated by Django 2.2.20 on 2021-04-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
